### ISSUE TITLE
AttributeError on opening .ptu created with Abberior Imspector

### ISSUE THREAD

**Issue by nranthony** [dwaithe/FCS_point_correlator#17]
Hi Dominic, I hope you can help.

I get the below error on opening a .ptu data set created with Abberior Imspector, using FoCuS_point_win_1_13_130.exe
Imspector version:  16.3.13036-w2049-win64

ptu file is here:  https://drive.google.com/file/d/1_TvT3HHLDENOMv8qZp3TNP3Xmpl4BKjH/view?usp=sharing
it's a crappy test data set of circular scanning, but I can get the time trace, pch, and acf using SymPhoTime, so I assume the file isn't corrupted.

Please let me know if there's anything I can do to help.  I'll download the repo and take a look under the hood in case there's anything that I'm able to help with.

Neil

```
Traceback (most recent call last):
  File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_gui", line 213, in showDialog
  File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_objects", line 60, in __init__
  File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\correlation_objects", line 78, in processData
  File "C:\cygwin64\home\dominic\build\FCS_point\out00-PYZ.pyz\import_methods", line 137, in ptuimport
AttributeError: 'int' object has no attribute 'astype'
```

**Comment by dwaithe** [comment]
Hi nrathony,
Thanks for you comment. That was a bug. In the latest release you will find that the problem has been fixed.
https://github.com/dwaithe/FCS_point_correlator/releases/tag/1.15.181
The mac version will come shortly. There are a few niggles still with Python 3. If you have any more problems, please let me know.
Best wishes,
Dominic.
